### ISSUE TITLE
Issue with Supercontrol within Matrix

### ISSUE THREAD

**Issue by tigerchick** [Goldinteractive/craft-sitecopy#11]
I installed this plugin and used it to copy a bunch of entries to numerous language version sites.
It copied the entry content successfully but if I then attempted to change the status of entries, roll back to previous versions of an entry, or even save an entry it threw an error when there are **Supertable fields within Matrix blocks** in the entry.
```
Invalid Configuration – [yii\base\InvalidConfigException](https://www.yiiframework.com/doc-2.0/yii-base-invalidconfigexception.html)
Invalid owner ID: xxxx
```

**Comment by lukasNo1** [comment]
This is probably a problem with the supertable plugin itself. Can you give me your Craft CMS and Plugin Versions to check?

**Comment by tigerchick** [comment]
@lukasNo1 sure, thanks for looking:

Craft Pro: 4.7.4
Supertable: 3.0.12
Gold sitecopy: 1.1.0

**Comment by lukasNo1** [comment]
Hey, I could not reproduce this issue.

If you can't rollback that means you revisions are broken too. Something must've gone wrong on a previous save with supertable / craft.

**Comment by tigerchick** [comment]
I can no longer reproduce this either so yes, I agree something must have gone wrong on a previous save with supertable / craft. Thanks for looking
