### ISSUE TITLE
FR: Copy to sites from Entries list

### ISSUE THREAD

**Issue by davorpeic** [Goldinteractive/craft-sitecopy#12]
Hi, 
I had case when x entries were created, and now they need to be copied to other site, so the only way is to open the entry and copy it, can you consider and estimate if would be worth adding option to select entries from the list and copy them to selected site?

Thanks
Davor

**Comment by lukasNo1** [comment]
Sounds like a good idea. I'll check if this is doable without consuming too much time. 

We would probably open a small overlay where you can select which sites to copy to.
Also we need to keep in mind the sections propagation method. If your propagation method is "Only save entries to the site they were created in" this still won't work, as we can only copy to entries that craft already created.

**Comment by davorpeic** [comment]
Awesome, yeah.. I think most of the sections have "Let the user decide" option selected, that is a step before creating, so that would also be challenging for that case right?

**Comment by lukasNo1** [comment]
Yeah, if you select two entries and one of them is not available in site x, we would need to hide the copy option to that site.
I will check though if we can make it work for the "Let the user decide" propagation method.

**Comment by lukasNo1** [comment]
I added the bulk copy feature in the new release 2.1.0 for craft 5. The "Let the user decide" propagation method now also works with sitecopy.

Feel free to test it out!
