### ISSUE TITLE
Select all not working on asset slide out panel in entry

### ISSUE THREAD

**Issue by yeboJoseph** [Goldinteractive/craft-sitecopy#16]
After clicking on an asset field to edit the image, I tried to select all to copy to sites but it didn't select all. Works as expected when I'm in Assets.

<img width="1308" alt="347242540-fa0600be-75ef-4e5e-afe4-a58781e8be04" src="https://github.com/user-attachments/assets/a898aea3-9a4c-42a7-8522-ee01b2f5c3f2">

**Comment by lukasNo1** [comment]
This is now fixed in the new release 2.1.1
