### ISSUE TITLE
Restrict use of plugin by user permissions

### ISSUE THREAD

**Issue by joshparylak** [Goldinteractive/craft-sitecopy#18]
Is there any way to restrict the use of this plugin? I'd like some content editors to have access to it, but others (who are limited to one site) should not be able to copy content to other sites.

**Comment by lukasNo1** [comment]
We check if the user has permission to the site he wants to copy to. If he does not, he won't be able to copy the entry.

Based on your description, content editors with access to only one site should already be restricted from copying content to other sites.

**Comment by joshparylak** [comment]
@lukasNo1 Ah, got it. That makes sense, and that's helpful. Does that affect the visibility of the copy option at all or does it appear regardless?

**Comment by lukasNo1** [comment]
If there is no site he can copy to at all, it will hide the whole widget in the sidebar.
