### ISSUE TITLE
Disable copy by default

### ISSUE THREAD

**Issue by BenPicard** [Goldinteractive/craft-sitecopy#3]
Hi,

Is it possible to disable the copy by default? (put the switch at OFF). It's causing problem if someone forgot to disable the copy when they save the page.

Regards

<img width="450" alt="Screen Shot 2022-12-21 at 1 32 38 PM" src="https://user-images.githubusercontent.com/6268293/208978411-c1c451c1-db9d-49d5-9b5b-bb3aa390e875.png">

**Comment by lukasNo1** [comment]
It should be disabled by default. Unless the automatic copy in the plugin settings is activated. Can you check if that's the case?

**Comment by BenPicard** [comment]
You are right. Thank you so much. The plugin is fantastic for our needs. Thank you for this work.
