### ISSUE TITLE
Sellect all

### ISSUE THREAD

**Issue by wmdhosting** [Goldinteractive/craft-sitecopy#4]
Can you add option Sellect All.  

So we can sellect all sites. instead clicking 1 by 1... 

I have 130 sites setup. and that will help :) quite

Thy

**Comment by lukasNo1** [comment]
Seems like a good option to add, i'll put it on my to-do list

**Comment by wmdhosting** [comment]
ok thx :)

**Comment by lukasNo1** [comment]
The select all checkbox is now added in the new release 1.0.6
