### ISSUE TITLE
Matrix fields on target translations become blank when Site Copy is used

### ISSUE THREAD

**Issue by japo32** [Goldinteractive/craft-sitecopy#5]
I have plain text fields and then Matrix fields with blocks.

The Block types have Entry fields, Plain Text fields, and Asset fields.

When I site copy to another translation, the blocks are created but they are blank.

I get an error like so, but these fields are filled out on the translation I have currently open:

<img width="454" alt="Screen Shot 2023-08-23 at 2 53 39 PM" src="https://github.com/Goldinteractive/craft-sitecopy/assets/676680/fa06957f-8ac0-4273-af20-d8f2c77f913e">

Then when you check the translation with the error, the Matrix fields are blank.

This was after upgrading from Craft CMS `4.4.17` to `4.5.0`

craft-sitecopy is `1.0.6` all the way.

I did a test by restoring a DB backup, and rolling back to the `4.4.17` codebase and matrix fields were being copied properly as expected.

**Comment by lukasNo1** [comment]
Hello, I found the problem and opened an issue with craft for it.
https://github.com/craftcms/cms/issues/13592
We'll fix it when the changes in 4.5.0 have been clarified

**Comment by lukasNo1** [comment]
hey @japo32, I just created a new release 1.0.7 with a workaround for this problem. Could you test if the plugin now works correctly on 4.5.0?

**Comment by japo32** [comment]
Wow so quick @lukasNo1 !
It looks like they've reverted the changes though. https://github.com/craftcms/cms/issues/13592#issuecomment-1690578442

I'll test out with both upgraded CMS and plugin.

**Comment by japo32** [comment]
Yeah looks like with that Craft CMS update, the workaround doesn't work.

**Comment by lukasNo1** [comment]
Yes, i saw that they reverted it :)
The workaround is unnecessary now with craft 4.5.1.

The copy should now work, correct?

**Comment by japo32** [comment]
Hi @lukasNo1 , Yep I've confirmed the plugin works as expected in these versions:

Craft CMS: `4.5.1`
Site Copy X: `1.0.6`

**Comment by japo32** [comment]
Just a note @lukasNo1 , it's broken with the latest release `1.0.7`.
Not sure what's the procedure for rolling back.

**Comment by lukasNo1** [comment]
Ok that is weird, as since Craft 4.5.1 the workaround shouldn't do anything.
i will make a new release to rollback the changes to be sure

**Comment by japo32** [comment]
Thanks @lukasNo1 . Craft 4.5.0 has been a rollercoaster for a few weeks based on the recent releases.
